//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSAdminsTime.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSAdminsTime.Common.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins are not configured.
        /// </summary>
        public static string Admins_not_configured {
            get {
                return ResourceManager.GetString("Admins_not_configured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find path &quot;{0}&quot;.
        /// </summary>
        public static string Cant_find_path_X {
            get {
                return ResourceManager.GetString("Cant_find_path_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration is not defined.
        /// </summary>
        public static string Configuration_not_defined {
            get {
                return ResourceManager.GetString("Configuration_not_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of administrators for add is &quot;{0}&quot;.
        /// </summary>
        public static string Count_of_administrators_for_add_X {
            get {
                return ResourceManager.GetString("Count_of_administrators_for_add_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of configured servers is &quot;{0}&quot;.
        /// </summary>
        public static string Count_of_configured_servers_is_X {
            get {
                return ResourceManager.GetString("Count_of_configured_servers_is_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File updated successfully.
        /// </summary>
        public static string File_updated_successfully {
            get {
                return ResourceManager.GetString("File_updated_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next execution at &quot;{0}&quot;.
        /// </summary>
        public static string Next_execution_at_X {
            get {
                return ResourceManager.GetString("Next_execution_at_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers are not configured.
        /// </summary>
        public static string Servers_not_configured {
            get {
                return ResourceManager.GetString("Servers_not_configured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong exception UID = &quot;{0}&quot;.
        /// </summary>
        public static string Something_went_wrong_exception_UID_X {
            get {
                return ResourceManager.GetString("Something_went_wrong_exception_UID_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start execution for server &quot;{0}&quot;.
        /// </summary>
        public static string Start_execution_for_server_X {
            get {
                return ResourceManager.GetString("Start_execution_for_server_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop execution for server &quot;{0}&quot;.
        /// </summary>
        public static string Stop_execution_for_server_X {
            get {
                return ResourceManager.GetString("Stop_execution_for_server_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying update file.
        /// </summary>
        public static string Trying_update_file {
            get {
                return ResourceManager.GetString("Trying_update_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update period.
        /// </summary>
        public static string Update_period {
            get {
                return ResourceManager.GetString("Update_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &quot;{0}&quot; is &quot;{1}&quot; this is bigger than maximum &quot;{2}&quot;.
        /// </summary>
        public static string X_is_Y_this_bigger_than_maximum_Z {
            get {
                return ResourceManager.GetString("X_is_Y_this_bigger_than_maximum_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &quot;{0}&quot; is &quot;{1}&quot; this is less than minimun &quot;{2}&quot;.
        /// </summary>
        public static string X_is_Y_this_less_than_minimun_Z {
            get {
                return ResourceManager.GetString("X_is_Y_this_less_than_minimun_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of  &quot;{0}&quot; will be set to &quot;{1}&quot;.
        /// </summary>
        public static string X_will_be_set_to_Y {
            get {
                return ResourceManager.GetString("X_will_be_set_to_Y", resourceCulture);
            }
        }
    }
}
