//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSAdminsTime.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSAdminsTime.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access flags.
        /// </summary>
        public static string Access_flags {
            get {
                return ResourceManager.GetString("Access_flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add admin(s) to server.
        /// </summary>
        public static string Add_admin_to_server {
            get {
                return ResourceManager.GetString("Add_admin_to_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new admin.
        /// </summary>
        public static string Add_new_admin {
            get {
                return ResourceManager.GetString("Add_new_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new server.
        /// </summary>
        public static string Add_new_server {
            get {
                return ResourceManager.GetString("Add_new_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins.
        /// </summary>
        public static string Admins {
            get {
                return ResourceManager.GetString("Admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t write exception.
        /// </summary>
        public static string Cant_write_exception {
            get {
                return ResourceManager.GetString("Cant_write_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection flags.
        /// </summary>
        public static string Connection_flags {
            get {
                return ResourceManager.GetString("Connection_flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create admin.
        /// </summary>
        public static string Create_admin {
            get {
                return ResourceManager.GetString("Create_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create server.
        /// </summary>
        public static string Create_server {
            get {
                return ResourceManager.GetString("Create_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error.
        /// </summary>
        public static string Critical_error {
            get {
                return ResourceManager.GetString("Critical_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit settings.
        /// </summary>
        public static string Edit_settings {
            get {
                return ResourceManager.GetString("Edit_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string End_date {
            get {
                return ResourceManager.GetString("End_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time.
        /// </summary>
        public static string End_time {
            get {
                return ResourceManager.GetString("End_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution started.
        /// </summary>
        public static string Execution_started {
            get {
                return ResourceManager.GetString("Execution_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution stopped.
        /// </summary>
        public static string Execution_stopped {
            get {
                return ResourceManager.GetString("Execution_stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify admin.
        /// </summary>
        public static string Modify_admin {
            get {
                return ResourceManager.GetString("Modify_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify server.
        /// </summary>
        public static string Modify_server {
            get {
                return ResourceManager.GetString("Modify_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name | IP | Steamid.
        /// </summary>
        public static string Name_IP_Steamid {
            get {
                return ResourceManager.GetString("Name_IP_Steamid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real name.
        /// </summary>
        public static string Real_name {
            get {
                return ResourceManager.GetString("Real_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove admin(s) from server.
        /// </summary>
        public static string Remove_admin_from_server {
            get {
                return ResourceManager.GetString("Remove_admin_from_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings and restart application for using selected language.
        /// </summary>
        public static string Save_and_restart_application_for_applying_language {
            get {
                return ResourceManager.GetString("Save_and_restart_application_for_applying_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save configuration.
        /// </summary>
        public static string Save_configuration {
            get {
                return ResourceManager.GetString("Save_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        public static string Servers {
            get {
                return ResourceManager.GetString("Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string Start_date {
            get {
                return ResourceManager.GetString("Start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start execution.
        /// </summary>
        public static string Start_execution {
            get {
                return ResourceManager.GetString("Start_execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string Start_time {
            get {
                return ResourceManager.GetString("Start_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop execution.
        /// </summary>
        public static string Stop_execution {
            get {
                return ResourceManager.GetString("Stop_execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update period.
        /// </summary>
        public static string Update_period {
            get {
                return ResourceManager.GetString("Update_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &quot;{0}&quot; can&apos;t be bigger than &quot;{1}&quot;.
        /// </summary>
        public static string X_cant_be_bigger_than_Y {
            get {
                return ResourceManager.GetString("X_cant_be_bigger_than_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &quot;{0}&quot; can&apos;t be less than &quot;{1}&quot;.
        /// </summary>
        public static string X_cant_be_less_than_Y {
            get {
                return ResourceManager.GetString("X_cant_be_less_than_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &quot;{0}&quot; is less or equals to &quot;{1}&quot;.
        /// </summary>
        public static string X_less_or_equals_Y {
            get {
                return ResourceManager.GetString("X_less_or_equals_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved settings. Save this settings before exit?.
        /// </summary>
        public static string You_have_unsaved_settings {
            get {
                return ResourceManager.GetString("You_have_unsaved_settings", resourceCulture);
            }
        }
    }
}
